on:
  push:
    tags:
      - '*'

jobs:

  test:

    name: ${{ matrix.lisp }}

    strategy:
      matrix:
        lisp: [sbcl]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Check $PATH
      run: echo $PATH

    - name: Add $CORE_NAME
      run: echo "CORE_NAME=moonli-${{ matrix.os }}-${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        OS: ${{ matrix.os }}
      run: |
        pwd
        ls -l
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Prepare moonli
      run: cl --eval '(push "./" ql:*local-project-directories*)' --eval '(ql:quickload "moonli")' --eval "(asdf:make :moonli)"


    - name: Rename moonli
      run: mv moonli $CORE_NAME

    - name: Compress moonli
      run: gzip $CORE_NAME

    - name: Upload moonli
      uses: actions/upload-artifact@v4
      with:
        name: moonli-${{ matrix.os }}-${{ github.ref_name }}.gz
        path: moonli-${{ matrix.os }}-${{ github.ref_name }}.gz

    - name: Publish moonli
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: moonli-${{ matrix.os }}-${{ github.ref_name }}.gz
